petstagram/accounts/urls.py
from django.urls import path, include

from petstagram.accounts.views import register_user, login_user, details_page, edit_page, delete_page

urlpatterns = (
    path('register/', register_user, name='register user'),
    path('login/', login_user, name='login user'),
    path('profile/<int:pk>/', include([
        path('', details_page, name='details page'),
        path('edit/', edit_page, name='edit page'),
        path('delete/', delete_page, name='delete page')
    ]))
)

petstagram/common/urls.py
from django.urls import path

from petstagram.common.views import home_page

urlpatterns = (
    path('', home_page, name='home page'),
)

petstagram/pets/urls.py
from django.urls import path, include

from petstagram.pets.views import add_pet, details_pet, edit_pet, delete_pet

urlpatterns = (
    path('add/', add_pet, name='add pet'),
    path('<str:username>/pet/<slug:pet_name>/', include([
        path('', details_pet, name='details pet'),
        path('edit/', edit_pet, name='edit pet'),
        path('delete/', delete_pet, name='delete pet'),
    ])),
)

petstagram/photos/urls.py
from django.urls import path, include

from petstagram.photos.views import add_photo, details_photo, edit_photo

urlpatterns = (
    path('add/', add_photo, name='add photo'),
    path('<int:pk>/', include([
        path('', details_photo, name='details photo'),
        path('edit/', edit_photo, name='edit photo'),
    ]))
)

petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

petstagram/accounts/models.py
from django.db import models

# Create your models here.

petstagram/common/models.py
from django.db import models

from petstagram.photos.models import Photo


class Comment(models.Model):
    TEXT_MAX_LEN = 300

    text = models.TextField(
        max_length=TEXT_MAX_LEN,
    )

    date_time_of_publication = models.DateTimeField(
        auto_now_add=True,
    )

    to_photo = models.ForeignKey(
        Photo,
        on_delete=models.CASCADE,
    )


class Like(models.Model):
    to_photo = models.ForeignKey(
        Photo,
        on_delete=models.CASCADE,
        null=False,
        blank=True,
    )


petstagram/pets/models.py
from django.db import models
from django.template.defaultfilters import slugify


# Create your models here.

class Pet(models.Model):
    MAX_NAME_LEN = 30

    name = models.CharField(
        max_length=MAX_NAME_LEN,
        null=False,
        blank=False,
    )

    personal_photo = models.URLField(
        null=False,
        blank=False,
    )

    data_of_birth = models.DateField(
        null=True,
        blank=True,
    )

    slug = models.SlugField(
        unique=True,
        null=False,
        blank=True,
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(f'{self.id}-{self.name}')

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram.pets.models import Pet
from petstagram.photos.validators import validate_file_size


class Photo(models.Model):
    DESC_MAX_LEN = 300
    DESC_MIN_LEN = 10
    LOCATION_MAX_LEN = 30

    photo = models.ImageField(
        null=False,
        blank=True,
        upload_to='mediafiles/pet-photos',
        validators=[
            validate_file_size,
        ],
    )

    description = models.TextField(
        null=True,
        blank=True,
        max_length=DESC_MAX_LEN,
        validators=[
            MinLengthValidator(DESC_MIN_LEN)
        ],
    )

    location = models.TextField(
        null=True,
        blank=True,
        max_length=LOCATION_MAX_LEN,
    )

    date_of_publication = models.DateField(
        null=False,
        blank=False,
        auto_now=True,
    )

    tagged_pets = models.ManyToManyField(
        Pet,
        blank=True,
    )

petstagram/accounts/views.py
from django.shortcuts import render


def login_user(request):
    return render(request, 'account/login-page.html')


def register_user(request):
    return render(request, 'account/register-page.html')


def delete_page(request, pk):
    return render(request, 'account/profile-delete-page.html')


def details_page(request, pk):
    return render(request, 'account/profile-details-page.html')


def edit_page(request, pk):
    return render(request, 'account/profile-edit-page.html')

petstagram/common/views.py
from django.shortcuts import render, redirect

from petstagram.common.models import Like
from petstagram.photos.models import Photo


def apply_likes_count(photo):
    photo.likes_count = photo.like_set.count()
    return photo


def apply_user_liked_photo(photo):
    photo.is_liked_by_user = photo.likes_count > 0
    return photo


def home_page(request):
    photos = [apply_likes_count(photo) for photo in Photo.objects.all()]
    photos = [apply_user_liked_photo(photo) for photo in photos]

    context = {
        'all_photos': photos,
    }

    return render(request, 'common/home-page.html', context=context)


def get_user_liked_current_photo(photo_id):
    return Like.objects.filter(to_photo_id=photo_id)


def like_photo(request, photo_id):
    user_liked_current_photo = get_user_liked_current_photo(photo_id)

    if user_liked_current_photo:
        user_liked_current_photo.delete()
    else:
        Like.objects.create(
            to_photo_id=photo_id,
        )

    return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')

petstagram/pets/views.py
from django.shortcuts import render


def add_pet(request):
    return render(request, 'pets/pet-add-page.html')


def delete_pet(request, username, pet_name):
    return render(request, 'pets/pet-delete-page.html')


def details_pet(request, username, pet_name):
    return render(request, 'pets/pet-details-page.html')


def edit_pet(request, username, pet_name):
    return render(request, 'pets/pet-edit-page.html')

petstagram/photos/views.py
from django.shortcuts import render


def add_photo(request):
    return render(request, 'photos/photo-add-page.html')


def details_photo(request, pk):
    return render(request, 'photos/photo-details-page.html')


def edit_photo(request, pk):
    return render(request, 'photos/photo-edit-page.html')

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}"
                         alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Login Page -->
                        <a href="#">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Register Page -->
                        <a href="">
                            <i>Register</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    {% block page_content %}
    {% endblock %}
</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/common/home-page.html
{% extends 'base/base.html' %}
{% load static %}
{% block page_content %}

    <div class="container">
        <div class="col-9">

            <!-- Start Searchbar Form -->
            <form class="searchbar" method="post">
                <input type="text" placeholder="Search by pet name...">
                <button>
                    <img src="{% static 'images/search.png' %}" height="18" alt="img2">
                </button>
            </form>
            <!-- End Searchbar Form -->

            <!-- Start Pet Photos Post Section -->
            {% for photo in all_photos %}
                <div class="card">

                    <!-- Start User Details and Image Location -->
                    <div class="top">
                        <div class="userDetails">
                            <!-- Link to User Profile Page -->
                            <a href="#">
                                <div class="profilepic">
                                    <div class="profile_img">
                                        <div class="image">
                                            <img src="{% static 'images/person.png' %}" alt="img8">
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <h3>
                                <!-- Link to User Profile Page -->
                                <a href="#">
                                    <!-- if user has first name and last name -->
                                    Diyan Kalaydzhiev
                                    <!-- else -->
                                    <!-- show user username -->
                                </a>
                                <br>
                                <!-- if the photo has location -->
                                {% if photo.location %}
                                    <span>{{ photo.location }}</span>
                                {% endif %}
                            </h3>
                        </div>
                    </div>
                    <!-- End User Details and Image Location -->

                    <!-- Start Pet Photo -->
                    <div class="imgBx" id="photo-{{ photo.pk }}">
                        <img src="{% static 'images/axolotl.jpeg' %}" alt="post" class="cover">
                    </div>
                    <!-- End Pet Photo -->

                    <!-- Start Like and Share Buttons -->
                    <div class="bottom">
                        <div class="actionBtns">
                            <div class="left">
                                <!-- Start Like Button -->
                                <span class="heart">
									<a href="{% url 'like photo' photo_id=photo.pk %}">
										<!-- if user has liked the photo -->
                                        {% if photo.is_liked_by_user %}
                                            <svg style="color: red"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 width="24"
                                                 height="24"
                                                 fill="currentColor"
                                                 class="bi bi-heart-fill"
                                                 viewBox="0 0 16 16">
                                            <!-- Coordinate path -->
                                            <path fill-rule="evenodd"
                                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                  fill="red">

                                            </path>
                                        </svg>
                                            <!-- else -->
                                        {% else %}
                                            <svg aria-label="Like"
                                                 color="#262626"
                                                 fill="#262626"
                                                 height="24"
                                                 role="img"
                                                 viewBox="0 0 48 48"
                                                 width="24">
                                        <!-- Coordinate path -->
                                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                        </path>
                                    </svg>
                                        {% endif %}
								</a>
								</span>
                                <!-- End Like Button -->

                                <!-- Start Share Button -->
                                <a href="">
                                    <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                                         height="24" role="img" viewBox="0 0 48 48" width="24">
                                        <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                                        </path>
                                    </svg>
                                </a>
                                <!-- End Share Button -->

                            </div>
                        </div>
                        <!-- End Like and Share Buttons -->

                        <!-- Number of Likes per Photo -->
                        <p class="likes">{{ photo.likes_count }} likes</p>

                        <!-- Start Tagged Pets -->
                        {% for pet in photo.tagged_pets.all %}

                            <!-- Link to First Tagged Pet Details Page-->
                            <a href="{% url 'details pet' username='koko' pet_name=pet.slug %}">
                                <p class="message">
                                    <b>{{ pet.name }}</b>
                                </p>
                            </a>
                            <!-- End Tagged Pets -->
                        {% endfor %}

                        <!-- Link to Photo Details Page -->
                        <a href="{% url 'details photo' pk=photo.pk %}">
                            <h4 class="details">See details</h4>
                        </a>

                        <!-- Date of Publication -->
                        <h5 class="postTime">{{ photo.date_of_publication }}</h5>

                        <!-- Start Add Comments Section -->
                        <div class="addComments">
                            <div class="reaction">
                                <h3>
                                    <i class="far fa-smile"></i>
                                </h3>
                            </div>
                            <!-- Start Add Comments Form -->
                            <form method="post" action="#">
                                <label for="id_body">Body:</label>
                                <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                          required="" id="id_body"></textarea>
                                <button type="submit">Post</button>
                            </form>
                            <!-- End Add Comments Form -->

                        </div>
                        <!-- End Add Comments Section -->

                    </div>
                </div>
                <!-- End Pet Photos Post Section -->
            {% endfor %}

        </div>
    </div>

{% endblock %}

templates/pets/pet-add-page.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- Start Add Pet Section-->
    <div class="edit-delete edit-photo">
        <h2>Add pet</h2>

        <!-- Start Add Pet Form -->
        <form action="#">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Pet name">
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date">
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image">
            </p>
            <!-- Add Pet Button -->
            <button class="add-btn" type="submit">Add Pet</button>
        </form>
        <!-- End Add Pet Form -->

    </div>
    <!-- End Add Pet Section -->

{% endblock %}

templates/pets/pet-delete-page.html
{% extends 'base/base.html' %}
{% block page_content %}
    <!-- Starts Delete Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Delete pet</h2>
        <!-- Starts Delete Pet Form -->
        <form action="#">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Name" value="Sasho" disabled>
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date" disabled>
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                       alt="pet image" disabled>
            </p>
            <!-- Delete Pet Button -->
            <button class="delete-btn" type="submit">Delete</button>
            <!-- Go Back Button -->
            <a class="btn btn-primary" href="javascript:history.back()">
                <button class="edit-btn" type="button">Go back</button>
            </a>
        </form>
        <!-- End Delete Pet Form -->
    </div>
    <!-- End Delete Pet Section -->
{% endblock %}

templates/pets/pet-edit-page.html
{% extends 'base/base.html' %}
{% block page_content %}
    <!-- Start Edit Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit Pet</h2>
        <!-- Start Edit Pet From -->
        <form action="">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Name" value="Sasho">
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date">
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                       alt="pet image">
            </p>
            <!-- Edit Pet Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Pet Form -->

    </div>
    <!-- End Edit Pet Section -->

{% endblock %}

templates/photos/photo-add-page.html
{% extends 'base/base.html' %}
{% block page_content %}
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
{% endblock %}

templates/photos/photo-edit-page.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

{% endblock %}